var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/report/calling/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1d0d17c4._.js")
R.c("server/chunks/ssr/node_modules_next_dist_cc88faaa._.js")
R.c("server/chunks/ssr/_f4ba0f04._.js")
R.c("server/chunks/ssr/[root-of-the-server]__5d06979b._.js")
R.c("server/chunks/ssr/[root-of-the-server]__655f8d11._.js")
R.c("server/chunks/ssr/node_modules_next_dist_a6fcb974._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_ece394eb.js")
R.c("server/chunks/ssr/_27011323._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_9774470f._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_45780354.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_15817684.js")
R.c("server/chunks/ssr/_124c2527._.js")
R.c("server/chunks/ssr/_next-internal_server_app_report_calling_page_actions_03b95abe.js")
R.m(15278)
module.exports=R.m(15278).exports
